### PR TITLE
wheels for Py 3.9

### LINKED ISSUE #84: wheels for Py 3.9
1. source install of pynng on linux for python 3.9  seems to work fine

2. is there any reason not to release wheels for python 3.9?

https://pypi.org/project/pynng/#files

### PR DESCRIPTION
**Pull request by Andrei-Pozolotin**
resolve #84

### CODE REVIEW

**Comment by codypiersall** [comment]
Thank you for this!

**Comment by Andrei-Pozolotin** [comment]
any chance of release?

image

**Comment by codypiersall** [comment]
Hahaha, sure!  Stay tuned...

**Comment by Andrei-Pozolotin** [comment]
`pynng-0.7.1-cp39-cp39-manylinux2010_x86_64.whl` works, thank you

**Pull request merged**
