### PR TITLE
Improve on the build process of this module

### PR DESCRIPTION
**Pull request by leonardp**
Adds a builder class for building mbedtls and nng.
Uses setup.cfg to specify the repo url and revision.

This should fix https://github.com/codypiersall/pynng/issues/1 and can be a step to solve https://github.com/codypiersall/pynng/issues/10 as well.

### CODE REVIEW

**Comment by codypiersall** [comment]
Hey @leonardp,  I really appreciate the time you've taken on this and I do like the approach.

Unfortunately some stuff in my personal life recently blew up (thankfully not involving health or family) so I do not know when I will have time to look at this in depth.

**Comment by leonardp** [comment]
Hello @codypiersall, I hope you are (doing) well.
I've looked at the state of python packaging and https://python-poetry.org/ looks like a future-proof candidate for packaging that
could be used today.
Would you be OK with moving to poetry? If so, I could give this a shot.

**Comment by wbadart** [comment]
@leonardp, I was a poetry user for a while (personally and professionally) and really like the project, but it has some shortcomings that ultimately pushed me back to setuptools. Namely, lack of support for [editable installs](https://github.com/python-poetry/poetry/issues/1279) and lack of support for [PEP 621](https://github.com/python-poetry/poetry/issues/3332). It's possible that neither of these are deal-breakers for pynng, but I'd personally recommend a build system with a better track record of standards adherence (e.g. [flit](https://flit.pypa.io/en/latest/), [pdm](https://pdm.fming.dev/), or of course (as of very recently) [setuptools](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html).

**Comment by codypiersall** [comment]
Took me over a year from the initial PR, but I finally merged this.  Your PR is *way* better than what I was doing before, so thank you!

**Pull request merged**
